### ISSUE TITLE
Knowledge cutoff date 

### ISSUE THREAD

**Issue by JeroenAdam** [deepseek-ai/DeepSeek-Coder-V2#1]
I couldn't find the knowledge cutoff date of DeepSeek-Coder-V2-Lite in the Readme.

**Comment by irthomasthomas** [comment]
Out of interest, why do model makers not make the cutoff date more prominent, or even not mention it at all? It seems like an very important detail - especially for coding models, where source-code and APIs change frequently. If you have the cutoff date, you can use RAG to add newer information to the context.

**Comment by JeroenAdam** [comment]
It looks quite promising, there are details in their paper:
![image](https://github.com/deepseek-ai/DeepSeek-Coder-V2/assets/16437621/c5c837a1-9112-40b5-b582-5d3fadb48178)

**Comment by guoday** [comment]
The knowledge cutoff date of DeepSeek-Coder-V2-Lite is November 2023, as described in Section 2 of the paper.
