### ISSUE TITLE
DeepSeek-Coder-V2-Lite model GPU/RAM requirement 

### ISSUE THREAD

**Issue by HashedViking** [deepseek-ai/DeepSeek-Coder-V2#11]
Hi, thank you for the amazing work! In the readme you say "**DeepSeek-Coder-V2 in BF16 format** for inference, 80GB*8 GPUs are required".
How much GPU/RAM is needed for inference for **DeepSeek-Coder-V2-Lite model**?

**Comment by guoday** [comment]
40GB *1 GPUs

**Comment by orderer0001** [comment]
> 40GB *1 GPUs in BF16 format

3*24G 4090 GPU doesn’t work?

**Comment by guoday** [comment]
> > 40GB *1 GPUs in BF16 format
> 
> 3*24G 4090 GPU doesn’t work?

If you have 3*24G 4090 GPUs, you need to enable TP 2 or PP 2. Alternatively, you can use the quantized version of the model on Ollama.

**Comment by czk32611** [comment]
> 40GB *1 GPUs in BF16 format

Could I ask the throughput on A100 40G?
