### ISSUE TITLE
Is the API pricing for the Deepseek v2 coder 230B model?

### ISSUE THREAD

**Issue by Hangsiin** [deepseek-ai/DeepSeek-Coder-V2#2]
The price of the API is really low, but I want to know if the large version of the model endpoint is correct.

I can't seem to find any information on it.

**Comment by neteroster** [comment]
It's the large one. The name is "Deepseek-Coder-V2" instead of "DeepSeek-V2-Lite".

**Comment by guoday** [comment]
The model on the platform is DeepSeek-Coder-V2 236B.

**Comment by Hangsiin** [comment]
> The model on the platform is DeepSeek-Coder-V2 236B.

Thank you for the amazing model release.

**Comment by hiber-niu** [comment]
Is the model on the platform  base or instruct version?
