### ISSUE TITLE
可以说明一下2024高考数学的评测方法和评测数据吗？

### ISSUE THREAD

**Issue by Chenzongchao** [deepseek-ai/DeepSeek-Coder-V2#8]

**Comment by Z000000** [comment]
同求阿里巴巴数学竞赛测评数据

**Comment by ZhihongShao** [comment]
评测数据：高考数学全国1卷选择题和填空题
评测方法：GPT-4o OCR问题，人工修正OCR错误。单选题提示只有一个选项对，多选题提示有多个对的选项，除此之外不加任何其他指令。所有模型的prompts保持一致。人工抽取模型预测结果并判分
